parameters:
- name: name
  type: string
- name: environments
  type: object
  default: {}
- name: interval
  type: number
  default: 3
- name: iterations
  type: number
  default: 5

stages:
- stage: '${{ parameters.name }}'
  jobs:
  - ${{ each env in parameters.environments }}:
    - job: ${{ parameters.name }}${{ env }}-prep
      displayName: Prep for ${{ parameters.name }}${{ env }}
      variables:
      - template: job-vars.yml
        parameters:
          name: ${{ parameters.name }}
          suffix: ${{ env }}
      steps:
      - task: PowerShell@2
        inputs:
          targetType: 'filePath'
          filePath: $(Build.Source)/scripts/job-prep.ps1
          arguments: -Environment $(envName)
    
    - job: ${{ parameters.name }}${{ env }}-longop
      dependsOn: ${{ parameters.name }}${{ env }}-prep
      displayName: Some Long Operation for ${{ parameters.name }}${{ env }}
      variables:
      - template: job-vars.yml
        parameters:
          name: ${{ parameters.name }}
          suffix: ${{ env }}
      steps:
      - task: PowerShell@2
        inputs:
          targetType: 'filePath'
          filePath: $(Build.Source)/scripts/job-long.ps1
